import { ProductStockRow } from './types';

export const mockStockRows: ProductStockRow[] = [
  {
    productId: 'prod-001',
    sku: 'ELEC-MON-24-BLK',
    productName: '24" IPS Monitor',
    categoryName: 'Electronics',
    uomSymbol: 'pcs',
    warehouseId: 'wh-001',
    warehouseName: 'Main Warehouse',
    locationId: 'loc-003',
    locationName: 'Rack A',
    onHandQty: 48,
    reservedQty: 12,
    availableQty: 36,
    stockStatus: 'IN_STOCK',
  },
  {
    productId: 'prod-002',
    sku: 'ELEC-KB-MEC-BLK',
    productName: 'Mechanical Keyboard',
    categoryName: 'Electronics',
    uomSymbol: 'pcs',
    warehouseId: 'wh-001',
    warehouseName: 'Main Warehouse',
    locationId: 'loc-003',
    locationName: 'Rack A',
    onHandQty: 5,
    reservedQty: 3,
    availableQty: 2,
    stockStatus: 'LOW_STOCK',
  },
  {
    productId: 'prod-003',
    sku: 'ELEC-MSE-WLES-GRY',
    productName: 'Wireless Mouse',
    categoryName: 'Electronics',
    uomSymbol: 'pcs',
    warehouseId: 'wh-001',
    warehouseName: 'Main Warehouse',
    locationId: 'loc-004',
    locationName: 'Rack B',
    onHandQty: 120,
    reservedQty: 20,
    availableQty: 100,
    stockStatus: 'IN_STOCK',
  },
  {
    productId: 'prod-004',
    sku: 'FURN-CHR-ERG-BLK',
    productName: 'Ergonomic Office Chair',
    categoryName: 'Furniture',
    uomSymbol: 'pcs',
    warehouseId: 'wh-001',
    warehouseName: 'Main Warehouse',
    locationId: 'loc-002',
    locationName: 'Stock',
    onHandQty: 0,
    reservedQty: 0,
    availableQty: 0,
    stockStatus: 'OUT_OF_STOCK',
  },
  {
    productId: 'prod-005',
    sku: 'STAT-PEN-BLU-PKT',
    productName: 'Ballpoint Pen (Blue) — 10pk',
    categoryName: 'Stationery',
    uomSymbol: 'pk',
    warehouseId: 'wh-001',
    warehouseName: 'Main Warehouse',
    locationId: 'loc-004',
    locationName: 'Rack B',
    onHandQty: 300,
    reservedQty: 50,
    availableQty: 250,
    stockStatus: 'IN_STOCK',
  },
  {
    productId: 'prod-006',
    sku: 'ELEC-MON-24-BLK',
    productName: '24" IPS Monitor',
    categoryName: 'Electronics',
    uomSymbol: 'pcs',
    warehouseId: 'wh-002',
    warehouseName: 'Hyderabad Warehouse',
    locationId: 'loc-008',
    locationName: 'Stock',
    onHandQty: 15,
    reservedQty: 10,
    availableQty: 5,
    stockStatus: 'LOW_STOCK',
  },
  {
    productId: 'prod-007',
    sku: 'ELEC-CAB-HDMI-2M',
    productName: 'HDMI Cable 2m',
    categoryName: 'Electronics',
    uomSymbol: 'pcs',
    warehouseId: 'wh-002',
    warehouseName: 'Hyderabad Warehouse',
    locationId: 'loc-008',
    locationName: 'Stock',
    onHandQty: 200,
    reservedQty: 0,
    availableQty: 200,
    stockStatus: 'IN_STOCK',
  },
  {
    productId: 'prod-008',
    sku: 'FURN-DESK-SIT-WHT',
    productName: 'Standing Desk (White)',
    categoryName: 'Furniture',
    uomSymbol: 'pcs',
    warehouseId: 'wh-002',
    warehouseName: 'Hyderabad Warehouse',
    locationId: 'loc-008',
    locationName: 'Stock',
    onHandQty: 0,
    reservedQty: 0,
    availableQty: 0,
    stockStatus: 'OUT_OF_STOCK',
  },
  {
    productId: 'prod-009',
    sku: 'PACK-BUBBLE-50M',
    productName: 'Bubble Wrap Roll 50m',
    categoryName: 'Packaging',
    uomSymbol: 'roll',
    warehouseId: 'wh-001',
    warehouseName: 'Main Warehouse',
    locationId: 'loc-001',
    locationName: 'Receiving',
    onHandQty: 8,
    reservedQty: 2,
    availableQty: 6,
    stockStatus: 'LOW_STOCK',
  },
  {
    productId: 'prod-010',
    sku: 'ELEC-UPS-650VA',
    productName: 'UPS 650VA',
    categoryName: 'Electronics',
    uomSymbol: 'pcs',
    warehouseId: 'wh-001',
    warehouseName: 'Main Warehouse',
    locationId: 'loc-003',
    locationName: 'Rack A',
    onHandQty: 22,
    reservedQty: 4,
    availableQty: 18,
    stockStatus: 'IN_STOCK',
  },
];
