package com.stocksense.inventory.balance;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity for the {@code inventory_balance} table (V002).
 * <p>
 * {@code availableQty} is a PostgreSQL GENERATED ALWAYS AS (on_hand_qty - reserved_qty) STORED
 * column.  It is mapped as read-only (insertable=false, updatable=false) so that
 * the DB remains the authoritative source — Hibernate never tries to write it.
 * <p>
 * {@code productId} and {@code locationId} are scalar UUID FKs (product owned by A,
 * location owned by A).
 * <p>
 * {@code version} drives optimistic locking.  However, the posting engine ALSO
 * uses pessimistic row locking ({@code SELECT ... FOR UPDATE}) for critical
 * inventory balance updates — optimistic locking alone is insufficient for
 * high-concurrency inventory scenarios.
 */
@Entity
@Table(name = "inventory_balance")
public class InventoryBalance {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** FK → product.id  (owned by A — scalar UUID) */
    @Column(name = "product_id", nullable = false)
    private UUID productId;

    /** FK → location.id  (owned by A — scalar UUID) */
    @Column(name = "location_id", nullable = false)
    private UUID locationId;

    @Column(name = "on_hand_qty", nullable = false, precision = 19, scale = 4)
    private BigDecimal onHandQty;

    @Column(name = "reserved_qty", nullable = false, precision = 19, scale = 4)
    private BigDecimal reservedQty;

    /**
     * Read-only.  Generated by PostgreSQL as {@code on_hand_qty - reserved_qty}.
     * The database value is the single authoritative source.
     */
    @Column(name = "available_qty", insertable = false, updatable = false,
            precision = 19, scale = 4)
    private BigDecimal availableQty;

    @Version
    @Column(name = "version", nullable = false)
    private Long version;

    /** Managed by DB trigger. */
    @Column(name = "updated_at", nullable = false, insertable = false, updatable = false)
    private Instant updatedAt;

    // ── Constructors ──────────────────────────────────────────────────────────

    public InventoryBalance() {}

    // ── Accessors ─────────────────────────────────────────────────────────────

    public UUID getId() { return id; }

    public UUID getProductId() { return productId; }
    public void setProductId(UUID productId) { this.productId = productId; }

    public UUID getLocationId() { return locationId; }
    public void setLocationId(UUID locationId) { this.locationId = locationId; }

    public BigDecimal getOnHandQty() { return onHandQty; }
    public void setOnHandQty(BigDecimal onHandQty) { this.onHandQty = onHandQty; }

    public BigDecimal getReservedQty() { return reservedQty; }
    public void setReservedQty(BigDecimal reservedQty) { this.reservedQty = reservedQty; }

    /** Read-only — computed by PostgreSQL. */
    public BigDecimal getAvailableQty() { return availableQty; }

    public Long getVersion() { return version; }

    public Instant getUpdatedAt() { return updatedAt; }

    // ── Pre-persist ───────────────────────────────────────────────────────────

    @PrePersist
    private void prePersist() {
        if (onHandQty == null) onHandQty = BigDecimal.ZERO;
        if (reservedQty == null) reservedQty = BigDecimal.ZERO;
        if (version == null) version = 0L;
    }
}
