import { BusinessPartner } from './types';

export const initialPartners: BusinessPartner[] = [
  {
    id: 'bp-001',
    name: 'Tata Steel Ltd',
    isSupplier: true,
    isCustomer: false,
    contactEmail: 'procurement@tatasteel.com',
    contactPhone: '+91-22-6665-5000',
    active: true,
  },
  {
    id: 'bp-002',
    name: 'Reliance Retail',
    isSupplier: false,
    isCustomer: true,
    contactEmail: 'orders@relianceretail.com',
    contactPhone: '+91-22-4455-6677',
    active: true,
  },
  {
    id: 'bp-003',
    name: 'Infosys Technologies',
    isSupplier: true,
    isCustomer: true,
    contactEmail: 'vendor@infosys.com',
    contactPhone: '+91-80-2852-0261',
    active: true,
  },
  {
    id: 'bp-004',
    name: 'Wipro Consumer Products',
    isSupplier: true,
    isCustomer: false,
    contactEmail: 'supply@wiproconsumer.com',
    contactPhone: '+91-80-2844-0011',
    active: true,
  },
  {
    id: 'bp-005',
    name: 'Flipkart Wholesale',
    isSupplier: false,
    isCustomer: true,
    contactEmail: 'b2b@flipkart.com',
    contactPhone: '+91-80-4909-2099',
    active: true,
  },
  {
    id: 'bp-006',
    name: 'HCL Supply Chain',
    isSupplier: true,
    isCustomer: true,
    contactEmail: 'scm@hcl.com',
    contactPhone: '+91-120-4250-000',
    active: false,
  },
  {
    id: 'bp-007',
    name: 'Mahindra Logistics',
    isSupplier: true,
    isCustomer: false,
    contactEmail: 'ops@mahindralogistics.com',
    contactPhone: '+91-22-2490-1441',
    active: true,
  },
];
