import { Location } from './types';

export const initialLocations: Location[] = [
  // Main Warehouse (wh-001)
  {
    id: 'loc-001',
    name: 'Receiving',
    code: 'WH/IN',
    locationType: 'INTERNAL',
    warehouseId: 'wh-001',
    parentLocationId: null,
    active: true,
  },
  {
    id: 'loc-002',
    name: 'Stock',
    code: 'WH/STOCK',
    locationType: 'INTERNAL',
    warehouseId: 'wh-001',
    parentLocationId: null,
    active: true,
  },
  {
    id: 'loc-003',
    name: 'Rack A',
    code: 'WH/STOCK/RACK-A',
    locationType: 'INTERNAL',
    warehouseId: 'wh-001',
    parentLocationId: 'loc-002',
    active: true,
  },
  {
    id: 'loc-004',
    name: 'Rack B',
    code: 'WH/STOCK/RACK-B',
    locationType: 'INTERNAL',
    warehouseId: 'wh-001',
    parentLocationId: 'loc-002',
    active: true,
  },
  {
    id: 'loc-005',
    name: 'Dispatch',
    code: 'WH/OUT',
    locationType: 'INTERNAL',
    warehouseId: 'wh-001',
    parentLocationId: null,
    active: true,
  },
  {
    id: 'loc-006',
    name: 'Transit (Outbound)',
    code: 'WH/TRANSIT',
    locationType: 'TRANSIT',
    warehouseId: 'wh-001',
    parentLocationId: null,
    active: true,
  },
  // Hyderabad Warehouse (wh-002)
  {
    id: 'loc-007',
    name: 'Receiving',
    code: 'HYD/IN',
    locationType: 'INTERNAL',
    warehouseId: 'wh-002',
    parentLocationId: null,
    active: true,
  },
  {
    id: 'loc-008',
    name: 'Stock',
    code: 'HYD/STOCK',
    locationType: 'INTERNAL',
    warehouseId: 'wh-002',
    parentLocationId: null,
    active: true,
  },
  {
    id: 'loc-009',
    name: 'Dispatch',
    code: 'HYD/OUT',
    locationType: 'INTERNAL',
    warehouseId: 'wh-002',
    parentLocationId: null,
    active: false,
  },
  // Virtual / global locations
  {
    id: 'loc-010',
    name: 'Vendors',
    code: 'VIRTUAL/VENDOR',
    locationType: 'VENDOR',
    warehouseId: null,
    parentLocationId: null,
    active: true,
  },
  {
    id: 'loc-011',
    name: 'Customers',
    code: 'VIRTUAL/CUSTOMER',
    locationType: 'CUSTOMER',
    warehouseId: null,
    parentLocationId: null,
    active: true,
  },
  {
    id: 'loc-012',
    name: 'Loss / Scrap',
    code: 'VIRTUAL/LOSS',
    locationType: 'LOSS',
    warehouseId: null,
    parentLocationId: null,
    active: true,
  },
];
